export const SPECIAL_USERNAMES = [
    '@admin',
    '@moderator',
    '@superadmin',
    '@support',
    '@help',
    '@team',
    '@staff',
    '@creator',
    '@verified',
    '@official',
    '@verifiedcreator',
    '@verifiedmodel',
    '@paymefans',
    '@paymefansofficial',
    '@paymefanssupport',
    '@paymefanshelp',
    '@paymefansteam',
    '@paymefanscreator',
    '@paymefansmodel',
    '@welcome',
    '@welcomecreator',
    '@technicalsupport',
    '@technicalhelp',
    '@technical',
    // '@dikewisdom',
    '@wisdom',
]