export const PERMISSIONS = {
      "admin": [
            "view:users",
            "view:posts",
            "view:comments",
            "view:messages",
            "view:transactions",
            "view:subscriptions",
            "view:models",
            "view:wallets",
            "view:settings",
            "view:reports",
            "view:analytics",
            "view:notifications",
            "view:content",
            "view:subscriptions",
            "view:subscription_tiers",
      ],
      "user": [
            "view:profile",
            "view:posts",
            "view:comments",
            "view:messages",
            "view:transactions",
            "view:subscriptions",
            "view:models",
            "view:wallets",
            "view:settings",
            "view:notifications",
            "view:content",
            "view:subscriptions",
      ],
      "model": [
            "view:profile",
            "view:posts",
            "view:comments",
            "view:messages",
            "view:transactions",
            "view:subscriptions",
            "view:models",
            "view:wallets",
            "view:settings",
            "view:notifications",
      ]
}
